// <auto-generated />
using System;
using CookbookPI.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CookbookPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200629145729_Initial Database")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CookbookPI.Models.Entities.Category", b =>
                {
                    b.Property<int>("ID_Category")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title");

                    b.HasKey("ID_Category");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CookbookPI.Models.Entities.Components", b =>
                {
                    b.Property<int>("ID_Component")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<int>("ID_Recipe");

                    b.Property<string>("NameOfComponent");

                    b.Property<string>("Unit");

                    b.HasKey("ID_Component");

                    b.HasIndex("ID_Recipe");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("CookbookPI.Models.Entities.Difficulty", b =>
                {
                    b.Property<int>("ID_Difficulty")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title");

                    b.HasKey("ID_Difficulty");

                    b.ToTable("Difficulty");
                });

            modelBuilder.Entity("CookbookPI.Models.Entities.NumberOfPeople", b =>
                {
                    b.Property<int>("ID_NumberOfPeople")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.HasKey("ID_NumberOfPeople");

                    b.ToTable("NumberOfPeople");
                });

            modelBuilder.Entity("CookbookPI.Models.Entities.Recipes", b =>
                {
                    b.Property<int>("ID_Recipe")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("ID_Category");

                    b.Property<int>("ID_Difficulty");

                    b.Property<int>("ID_NumberOfPeople");

                    b.Property<int>("ID_TimeOfPrepare");

                    b.Property<int>("ID_TypeOfKitchen");

                    b.Property<int>("ID_User");

                    b.Property<string>("Instruction");

                    b.Property<bool>("IsAccepted");

                    b.Property<byte[]>("Photo");

                    b.Property<string>("Title");

                    b.HasKey("ID_Recipe");

                    b.HasIndex("ID_Category");

                    b.HasIndex("ID_Difficulty");

                    b.HasIndex("ID_NumberOfPeople");

                    b.HasIndex("ID_TimeOfPrepare");

                    b.HasIndex("ID_TypeOfKitchen");

                    b.HasIndex("ID_User");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("CookbookPI.Models.Entities.TimeOfPrepares", b =>
                {
                    b.Property<int>("ID_TimeOfPrepares")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TimeOfPrepare");

                    b.HasKey("ID_TimeOfPrepares");

                    b.ToTable("TimeOfPrepares");
                });

            modelBuilder.Entity("CookbookPI.Models.Entities.TypeOfKitchen", b =>
                {
                    b.Property<int>("ID_TypeOfKitchen")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title");

                    b.HasKey("ID_TypeOfKitchen");

                    b.ToTable("TypeOfKitchen");
                });

            modelBuilder.Entity("CookbookPI.Models.Entities.User_Permission", b =>
                {
                    b.Property<int>("ID_Permission")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title");

                    b.HasKey("ID_Permission");

                    b.ToTable("User_Permissions");
                });

            modelBuilder.Entity("CookbookPI.Models.Entities.Users", b =>
                {
                    b.Property<int>("ID_User")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfRegistration");

                    b.Property<string>("Email");

                    b.Property<int>("ID_Permission");

                    b.Property<string>("Nickname");

                    b.Property<string>("Passwrd");

                    b.Property<bool>("isBanned");

                    b.HasKey("ID_User");

                    b.HasIndex("ID_Permission");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CookbookPI.Models.Entities.Components", b =>
                {
                    b.HasOne("CookbookPI.Models.Entities.Recipes", "Recipes")
                        .WithMany()
                        .HasForeignKey("ID_Recipe")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CookbookPI.Models.Entities.Recipes", b =>
                {
                    b.HasOne("CookbookPI.Models.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("ID_Category")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CookbookPI.Models.Entities.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("ID_Difficulty")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CookbookPI.Models.Entities.NumberOfPeople", "NumberOfPeople")
                        .WithMany()
                        .HasForeignKey("ID_NumberOfPeople")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CookbookPI.Models.Entities.TimeOfPrepares", "TimeOfPrepares")
                        .WithMany()
                        .HasForeignKey("ID_TimeOfPrepare")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CookbookPI.Models.Entities.TypeOfKitchen", "TypeOfKitchen")
                        .WithMany()
                        .HasForeignKey("ID_TypeOfKitchen")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CookbookPI.Models.Entities.Users", "Users")
                        .WithMany()
                        .HasForeignKey("ID_User")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CookbookPI.Models.Entities.Users", b =>
                {
                    b.HasOne("CookbookPI.Models.Entities.User_Permission", "User_Permission")
                        .WithMany()
                        .HasForeignKey("ID_Permission")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
